// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDaGjvTiKssnVCHOudzBLdFKE0T-eXq3s',
    appId: '1:948610844633:web:44936b5d9a29e4c906fbc8',
    messagingSenderId: '948610844633',
    projectId: 'latihanuasmulplat',
    authDomain: 'latihanuasmulplat.firebaseapp.com',
    storageBucket: 'latihanuasmulplat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpyAlXzVmILAKW33eZVD65-u433smtlyU',
    appId: '1:948610844633:android:0ea8a2b2a556a3b806fbc8',
    messagingSenderId: '948610844633',
    projectId: 'latihanuasmulplat',
    storageBucket: 'latihanuasmulplat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC78c7l7QODYtNJD7yU-hOwk9uIDfe0PMY',
    appId: '1:948610844633:ios:bd66d44d44a8123006fbc8',
    messagingSenderId: '948610844633',
    projectId: 'latihanuasmulplat',
    storageBucket: 'latihanuasmulplat.appspot.com',
    iosClientId: '948610844633-k0d29db46k794oighoib0d6fqhmu91f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanuas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC78c7l7QODYtNJD7yU-hOwk9uIDfe0PMY',
    appId: '1:948610844633:ios:34ad663eb0558e7906fbc8',
    messagingSenderId: '948610844633',
    projectId: 'latihanuasmulplat',
    storageBucket: 'latihanuasmulplat.appspot.com',
    iosClientId: '948610844633-ho45snl4gjp96dpkh42bfagqt6vhlb5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanuas.RunnerTests',
  );
}
